name: proup
description: "Android Launcher for productivity."
publish_to: "Skepr"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  hijri: ^3.0.0
  intl: ^0.20.1
  battery_plus: ^6.2.1
  external_app_launcher: ^4.0.1
  adhan: ^2.0.0+1
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.4.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Misans
      fonts:
        - asset: assets/fonts/شاومي.otf
          style: normal
